# Generated by Django 2.2 on 2021-07-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='notes'),
            preserve_default=False,
        ),
    ]
